; Description

; text             = main text, playlist names in main field, name of playlist selected in sidebar, headings
; subtext          = text in main buttons in sidebar, playlist names in sidebar, artist names, and mini infos
; nav-active-text  = text in main buttons in sidebar when active
; main             = main bg
; main-secondary   = bg color of selected song rows, bg color of artist/track cards
; sidebar          = sidebar bg
; player           = player bg
; card             = popup-card bg
; shadow           = all shadows
; button           = playlist buttons bg in sidebar, drop-down menus, now playing song, like button
; button-secondary = download and options button
; button-active    = hover on song selected
; button-disabled  = seekbar bg, volume bar bg, scrollbar
; nav-active       = sidebar buttons bg
; play-button      = color of main play button in main field
; tab-active       = button bg in main field (playlists, podcasts, artists, albums)
; notification     = notification ('Added to liked songs' etc.)
; playback-bar     = seekbar fg, volume bar fg, main play/pause button
; misc             = miscellaneous

[Base]
text               = 4d8cc4
subtext            = cfdceb
nav-active-text    = 10171e
main               = 10171e
sidebar            = 10171e
player             = 10171e
card               = 10171e
shadow             = 000000
main-secondary     = 556072
button             = 4d8cc4
button-secondary   = cfdceb
button-active      = 0bde96
button-disabled    = 556072
nav-active         = 4d8cc4
play-button        = 4d8cc4
tab-active         = 556072
notification       = 556072
notification-error = 556072
playback-bar       = 4d8cc4
misc               = cfdceb
