# fzf colors, generated by Themer, sourced from .zshrc
export FZF_THEMER_COLORS="--color=bg+:{{ surface-hover }},bg:{{ bg }},fg:{{ text }},fg+:{{ text-bright }},hl:{{ accent }},hl+:{{ accent-hover }},info:{{ text-subtle }},prompt:{{ accent }},pointer:{{ accent }},marker:{{ success }},spinner:{{ cyan }},header:{{ text-subtle }},border:{{ line-strong }},gutter:{{ bg }}"
