; Description

; text             = main text, playlist names in main field, name of playlist selected in sidebar, headings
; subtext          = text in main buttons in sidebar, playlist names in sidebar, artist names, and mini infos
; nav-active-text  = text in main buttons in sidebar when active
; main             = main bg
; main-secondary   = bg color of selected song rows, bg color of artist/track cards
; sidebar          = sidebar bg
; player           = player bg
; card             = popup-card bg
; shadow           = all shadows
; button           = playlist buttons bg in sidebar, drop-down menus, now playing song, like button
; button-secondary = download and options button
; button-active    = hover on song selected
; button-disabled  = seekbar bg, volume bar bg, scrollbar
; nav-active       = sidebar buttons bg
; play-button      = color of main play button in main field
; tab-active       = button bg in main field (playlists, podcasts, artists, albums)
; notification     = notification ('Added to liked songs' etc.)
; playback-bar     = seekbar fg, volume bar fg, main play/pause button
; misc             = miscellaneous

[Base]
text               = {blue4}
subtext            = {foreground}
nav-active-text    = {background}
main               = {background}
sidebar            = {background}
player             = {background}
card               = {background}
shadow             = 000000
main-secondary     = {grey5}
button             = {blue4}
button-secondary   = {foreground}
button-active      = {green5}
button-disabled    = {grey5}
nav-active         = {blue4}
play-button        = {blue4}
tab-active         = {grey5}
notification       = {grey5}
notification-error = {grey5}
playback-bar       = {blue4}
misc               = {foreground}
